name: Formatters

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatter:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check examples/ src/ tests/

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  # TODO: Address failing issue 
  # clippy:
  #   name: Clippy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: 1.57.0
  #         override: true
  #         components: clippy
  #     - uses: actions-rs/clippy-check@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         args: -- -D warnings
